# Generated by Django 3.1.5 on 2021-08-10 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('apellidopaterno', models.CharField(max_length=80)),
                ('apellidomaterno', models.CharField(max_length=80)),
                ('empresa', models.CharField(max_length=80)),
                ('correo', models.CharField(max_length=80)),
                ('contrasena', models.CharField(max_length=80)),
                ('fechacompleta', models.DateTimeField()),
                ('autorizado', models.BooleanField()),
            ],
        ),
    ]
