# Generated by Django 3.1.5 on 2021-08-10 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appQuart', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
