# Generated by Django 3.1.5 on 2021-08-10 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appQuart', '0003_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
